### PR TITLE
Add script to clean OLD AMIs worldwide

### LINKED ISSUE #18: Add script to clean old images
Removing public images from every AWS zone is a repetitive and long task that can be automated

### PR DESCRIPTION
**Pull request by eskombro**
Closes #18

### CODE REVIEW

**Review by curquiza — COMMENTED** [review]
Just to be sure, do you need to delete the image one by one?
Which image would we want to delete (for example)? Do we want to only keep the last one?
This should be written in the CONTRIBUTING? I'm wondering if it should become a mandatory step :)

**Comment by curquiza** [comment]
PS : git conflict 😭 😂

**Comment by eskombro** [comment]
> Just to be sure, do you need to delete the image one by one?

On the AWS interface you need to manually change the zone and delete the AMI, one by one, by hand.
As we will normally create an AMI with the same name in every AWS region, this script deletes all the AMIs of every AWS zone with the specified *name*, so we can decide to delete one single version, but worldwide, all at once.

We will probably delete one single version anyways every time we release a new one.

> Which image would we want to delete (for example)? Do we want to only keep the last one?
> This should be written in the CONTRIBUTING? I'm wondering if it should become a mandatory step :)

We haven't decided if we want to keep older versions available, but with this tool, it will be very easy to clean anything we need to clean. I think we should at least have the last 2 versions, in case the new one has a bug or a problem, so users can install the older version while the latest is fixed, WDYT @curquiza ?

I can add on the contributing:

```
Make sure that the last 2 versions of MeilISearch AMI are available and public in every AWS region, and use the `unpublish-image.py` script to delete every other AMI that is present in AWS
```

For example

**Comment by curquiza** [comment]
I think the two last versions is a good idea :) Adding it to the CONTRIBUTING is a good idea too

**Review by curquiza — APPROVED** [review]
🎉

**Pull request merged**
